Gradle home work
brownynik/otus-homeworks pull request #1
Opened 2023-05-21 19:28 UTC by brownynik

2023-05-30 11:02 UTC, javaotus requested changes

2023-05-30 11:02 UTC, javaotus commented on hw01-gradle/src/main/java/ru/otus/homeworkmodule/HelloOtus.java
> +        buf.add((String) null);
Зачем тут это приведение типа? Аргумент же как null идёт.

2023-05-30 11:02 UTC, javaotus commented on hw01-gradle/src/main/java/ru/otus/homeworkmodule/HelloOtus.java
> +        StringBuffer sbResult = new StringBuffer();
А почему не StringBuilder ?

2023-05-30 11:02 UTC, javaotus commented on hw01-gradle/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
Вы либо пишите в kotlin style либо в java style.
Не думаю, что стоит комбинировать.

2023-05-30 11:02 UTC, javaotus commented on hw01-gradle/src/main/java/ru/otus/homeworkmodule/HelloOtus.java
> +        System.out.println("Without Guava Variant: " + sbResult.toString());
System.out.println и так по умолчанию конвертирует в String, не нужно вызывать toString() лишний раз.

2023-05-30 11:02 UTC, javaotus commented on src/main/java/ru/otus/homework/Main.java
> +        // runtime error: error: package ru.otus.homeworkmodule does not exist
зачем тут эти комментарии? не нужно отправлять комментарии в комиты.

2023-06-06 16:49 UTC, brownynik commented on hw01-gradle/src/main/java/ru/otus/homeworkmodule/HelloOtus.java
> +        buf.add((String) null);
Привычка кастовать null для точного соответствия ожидаемому типу.  В некоторых случаях (я не говорю про Java) это имеет значение - например, если выборку MS-SQL явно не кастовать, можно получить схему данных, не соответствующую ожиданиям. Если в случае с Java это вредно, напишите. Я абсолютный новичок в Java.

2023-06-06 16:50 UTC, brownynik commented on hw01-gradle/src/main/java/ru/otus/homeworkmodule/HelloOtus.java
> +        StringBuffer sbResult = new StringBuffer();
Просто потому что такой вариант написал, руководствуясь базовыми знаниями по языку. Это имеет значение в данном случае? Пожалуйста, напишите, почему Вы так считаете.

2023-06-06 16:51 UTC, brownynik commented on hw01-gradle/build.gradle
> +    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
Исправил. Да, некрасиво. Привёл к единому формату.

2023-06-06 16:52 UTC, brownynik commented on hw01-gradle/src/main/java/ru/otus/homeworkmodule/HelloOtus.java
> +        System.out.println("Without Guava Variant: " + sbResult.toString());
Это имеет практическое значение или просто делает код более компактным? Опять же, стараюсь явно кастовать к заданному типу. Если это вредно, напишите, пожалуйста.

2023-06-06 16:52 UTC, brownynik commented on src/main/java/ru/otus/homework/Main.java
> +        // runtime error: error: package ru.otus.homeworkmodule does not exist
Почему я не могу оставлять комментарии в ученическом коде? А как лучше размещать такую вспомогательную информацию?

2023-06-06 17:02 UTC, closed without merging

2023-06-06 17:03 UTC, brownynik commented
Неудачная редакция - не будет размещено в prod ветку